# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &f아머스탠드 &6| &r'

